1:
  start: { 'y': 33.62809938, 'x': -84.4331128 }
  end: { 'y': 33.624940870, 'x': -84.433553779 }

2:
  start: { 'y': 33.6355165, 'x': -84.4419355 }
  end: { 'y': 33.631830, 'x': -84.438417 }

3:
  start: { 'y': 33.629219, 'x': -84.424368 }
  end: { 'y': 33.63072962, 'x': -84.41916982 }

4:
  start: { 'y': 33.6258989, 'x': -84.4285351 }
  end: { 'y': 33.631617, 'x': -84.418729 }

5:
  start: { 'y': 33.6370117, 'x': -84.427330 }
  end: { 'y': 33.631836, 'x': -84.428784 }

6:
  start: { 'y': 33.634721078, 'x': -84.428451061 }
  end: { 'y': 33.64098882, 'x': -84.42104330 }
